### ISSUE TITLE
Trying to run dimple on android phone

### ISSUE THREAD

**Issue by pramodatre** [AnalogDevicesLyricLabs/dimple#12]
Hi,

I'm trying to run dimple on android phone. I was able to build the android project successfully. However, when I try to run the code, here is the error message I get:

```
04-18 14:07:06.695 30424-30424/com.example.anp2pi.myfirstapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.example.anp2pi.myfirstapp, PID: 30424
                                                                               java.lang.NoClassDefFoundError: com.analog.lyric.options.OptionKeys$DeclaredOptionKeys
                                                                                   at com.analog.lyric.options.OptionKeys.<clinit>(OptionKeys.java:69)
                                                                                   at com.analog.lyric.options.OptionKeys.declaredInClass(OptionKeys.java:150)
                                                                                   at com.analog.lyric.options.OptionRegistry.addFromClasses(OptionRegistry.java:207)
                                                                                   at com.analog.lyric.dimple.options.DimpleOptionRegistry.<init>(DimpleOptionRegistry.java:95)
                                                                                   at com.analog.lyric.dimple.environment.DimpleEnvironment.<init>(DimpleEnvironment.java:209)
                                                                                   at com.analog.lyric.dimple.environment.DimpleEnvironment.<init>(DimpleEnvironment.java:238)
                                                                                   at com.analog.lyric.dimple.environment.DimpleEnvironment.defaultEnvironment(DimpleEnvironment.java:298)
                                                                                   at com.analog.lyric.dimple.environment.DimpleEnvironment$1.initialValue(DimpleEnvironment.java:153)
                                                                                   at com.analog.lyric.dimple.environment.DimpleEnvironment$1.initialValue(DimpleEnvironment.java:149)
                                                                                   at java.lang.ThreadLocal$Values.getAfterMiss(ThreadLocal.java:430)
                                                                                   at java.lang.ThreadLocal.get(ThreadLocal.java:65)
                                                                                   at com.analog.lyric.dimple.environment.DimpleEnvironment.active(DimpleEnvironment.java:317)
                                                                                   at com.analog.lyric.dimple.model.core.FactorGraph.<init>(FactorGraph.java:762)
                                                                                   at com.analog.lyric.dimple.model.core.FactorGraph.<init>(FactorGraph.java:741)
                                                                                   at com.example.anp2pi.myfirstapp.DisplayMessageActivity.onCreate(DisplayMessageActivity.java:24)
                                                                                   at android.app.Activity.performCreate(Activity.java:6536)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3238)
                                                                                   at android.app.ActivityThread.access$1000(ActivityThread.java:197)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6862)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
04-18 14:07:07.855 30424-30424/com.example.anp2pi.myfirstapp I/Process: Sending signal. PID: 30424 SIG: 9

```

Any suggestion on getting this working will be great!

Thanks a lot in advance!

Best,
Pramod.

**Comment by analog-cbarber** [comment]
[This is issue #394 in our internal bug tracking system]

We do not officially support Android. However, I believe that one known difference between Android and the standard JRE for Java 7 is that there is no ClassValue implementation. So either you need to fork Dimple and replace ClassValue with some other lazy caching implementation or wait until a version of Android comes out that supports it. I have heard that Nougat may include ClassValue, but do not know for sure.

**Comment by analog-cbarber** [comment]
FYI, I don't see ClassValue in the online API ref for the [java.lang package in Android API level 24 ](https://developer.android.com/reference/java/lang/package-summary.html
)(Nougat).
